### ISSUE TITLE
Float division by zero

### ISSUE THREAD

**Issue by sigod** [imgrant/fit2tcx#1]
```
>fit2tcx.exe file_1.fit file_2.tcx
Traceback (most recent call last):
  File "<string>", line 1044, in <module>
  File "<string>", line 1028, in main
  File "<string>", line 884, in convert
  File "<string>", line 819, in add_activity
  File "<string>", line 707, in add_lap
ZeroDivisionError: float division by zero
fit2tcx returned -1
```

Ask me if you need actual FIT file.

**Comment by imgrant** [comment]
What version are you using? There was a fix for zero division errors in this region in version 1.5.

**Comment by sigod** [comment]
I believe I've tried to use the latest version from releases. So, it would be 1.2.

**Comment by imgrant** [comment]
In that case, please try the latest (1.6) instead -- either the python script or compile into .exe if you need.
